-- 
  CREATE TABLE "SHOP"."MEMBERTBL" 
   (	"MEMBERID" CHAR(8 BYTE) NOT NULL ENABLE, 
	"MEMBERNAME" NCHAR(5) NOT NULL ENABLE, 
	"MEMBERADDRESS" NVARCHAR2(20), 
	 CONSTRAINT "MEMBERTBL_PK" PRIMARY KEY ("MEMBERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;


--
INSERT INTO "SHOP"."MEMBERTBL" (MEMBERID, MEMBERNAME, MEMBERADDRESS) VALUES ('Dang', N'당탕이', N'경기 부천시 중동');
INSERT INTO "SHOP"."MEMBERTBL" (MEMBERID, MEMBERNAME, MEMBERADDRESS) VALUES ('Jee', N'지운이', N'서울 은평구 증산동');
INSERT INTO "SHOP"."MEMBERTBL" (MEMBERID, MEMBERNAME, MEMBERADDRESS) VALUES ('Han', N'한주연', N'인천 남구 주안동');
INSERT INTO "SHOP"."MEMBERTBL" (MEMBERID, MEMBERNAME, MEMBERADDRESS) VALUES ('Sang', N'상길이', N'경기 성남시 분당구');


--
  CREATE TABLE "SHOP"."PRODUCTTBL" 
   (	"PRODUCTNAME" NCHAR(4) NOT NULL ENABLE, 
	"COST" NUMBER(7,0) NOT NULL ENABLE, 
	"MAKEDATE" DATE, 
	"COMPANY" NCHAR(5), 
	"AMOUNT" NUMBER(3,0) NOT NULL ENABLE, 
	 CONSTRAINT "PRODUCTTBL_PK" PRIMARY KEY ("PRODUCTNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
  
  --
INSERT INTO "SHOP"."PRODUCTTBL" (PRODUCTNAME, COST, MAKEDATE, COMPANY, AMOUNT) VALUES (N'컴퓨터', '10', TO_DATE('2017-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), N'삼성', '17');
INSERT INTO "SHOP"."PRODUCTTBL" (PRODUCTNAME, COST, MAKEDATE, COMPANY, AMOUNT) VALUES (N'세탁기', '20', TO_DATE('2018-09-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), N'LG', '3');
INSERT INTO "SHOP"."PRODUCTTBL" (PRODUCTNAME, COST, MAKEDATE, COMPANY, AMOUNT) VALUES (N'냉장고', '5', TO_DATE('2019-02-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), N'대우', '22');

--
SELECT *
FROM MEMBERTBL
WHERE 1 = 1
;

-- PRESS F10 ON THIS SQL
SELECT *
FROM INDEXTBL
WHERE 1 = 1
AND FIRST_NAME = 'Jack'
;

--
CREATE INDEX IDX_INDEXTBL_FIRSTNAME ON INDEXTBL(FIRST_NAME);

--
SELECT *
FROM MEMBERTBL_VIEW
WHERE 1 = 1
;

--
SELECT COUNT(*) FROM MEMBERTBL;
SELECT COUNT(*) FROM PRODUCTTBL;

--
SET SERVEROUTPUT ON;

--
EXECUTE MYPROC;


--
CREATE TABLE DELETEDMEMBERTBL (
    MEMBERID CHAR(8),
    MEMBERNAME NCHAR(5),
    MEMBERADDRESS NVARCHAR2(20),
    DELETEDDATE DATE
)
;


--
CREATE TRIGGER TRIG_DELETEDMEMBER_TBL
    AFTER DELETE
    ON MEMBERTBL
    FOR EACH ROW
    BEGIN
        INSERT INTO DELETEDMEMBERTBL
        VALUES (
              :OLD.MEMBERID
            , :OLD.MEMBERNAME
            , :OLD.MEMBERADDRESS
            , SYSDATE()
        )
        ;
    END;
    
--
DELETE FROM MEMBERTBL WHERE MEMBERNAME = '당탕이';

--
SELECT *
FROM DELETEDMEMBERTBL
WHERE 1 = 1
;