--
CREATE TABLE SHOP.INDEXTBL
AS (
    SELECT FIRST_NAME
         , LAST_NAME
         , HIRE_DATE
    FROM HR.EMPLOYEES
)
;


--
CREATE VIEW SHOP.MEMBERTBL_VIEW AS (
    SELECT MEMBERNAME
         , MEMBERADDRESS
    FROM SHOP.MEMBERTBL
)
;

--
CREATE PROCEDURE SHOP.MYPROC AS
    VAR1 INT;
    VAR2 INT;    
BEGIN
    SELECT COUNT(*) INTO VAR1 FROM SHOP.MEMBERTBL;
    SELECT COUNT(*) INTO VAR2 FROM SHOP.PRODUCTTBL;
    DBMS_OUTPUT.PUT_LINE(VAR1 + VAR2);
END;